/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c4257bce-5f8d-4eed-b99c-f463883ff193",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_y8gyDqoG2",
    "aws_user_pools_web_client_id": "1m2vmntjgaio3ltcgc7c0um8dn",
    "oauth": {},
    "aws_user_files_s3_bucket": "mockbookstoree165133e99c442c7bf45ef1ac6304840185348-prod",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://gt4l2epsijgy5bmci43diitpsq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-tufrjjs3zzfc5kmjtbcft53jxu",
    "aws_content_delivery_bucket": "mockbookstore-20201230000636-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://mockbookstore-20201230000636-hostingbucket-prod.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
